### PR TITLE
Add colors to Table css, style Details

### PR DESCRIPTION
**Pull request by iloveMonday**
Put together something of a color pallet, but my monitor and my Thinkpad are giving me very different hues lol. 
Not sure if I was working in the correct css file, but here it is.
Added some className tags, not sure if I went about stylizing in the cleanest way.
Added a space for album art in the collapsing Details tab. Figured it'd be helpful if you're referencing this while digging through your bins. Also figured the printable version wouldn't include this. Had trouble figuring out how to link it from a folder. Is it possible to get it from the API? I don't know anything about working with them.

### CODE REVIEW

**Comment by JarrettD5309** [comment]
Thanks for taking the first steps here! A few things:
1. CSS files should generally be organized in a standard way. You can definitely look up articles about this but it goes something like: Up top we have very high level stuff like universal colors and fonts and things applied to the 'body' tag. After that top level stuff, everything else should be alphabetical by section. The sections in order are A. Html Tags (such as 'h1', 'p', 'button', etc), B. class tags ('.click-hand', etc), and then C. ids ('#special-row'). There are exceptions but this will apply to 95% of our CSS work.
2. When building an app with component structure, we should try to bundle all the pieces of that specific component as tightly to it as possible. With respect to our project, this means the CSS for the class '.genre-button' should be in a CSS file associated with 'App.tsx' not the CSS file in the Table component. This opens a can of worms though. Why does '.genre-button' style work even though it is currently in the wrong place? Because by default CSS files in React projects are global. This causes a huge headache, especially as projects grow. If you have 50 components, you have to ask yourself "Did I already use the class name '.row-red'?". Check out this article for more info about it. https://dev.to/eransakal/how-to-isolate-component-styles-in-react-using-css-modules-mkm For now we can just move the styles for 'genre-button' into the correct CSS file.

**Comment by iloveMonday** [comment]
1. Thanks for that breakdown! This makes a lot more sense than how I've generally organized stylesheets on all my single-page projects, with high level stuff first and then just following the flow of HTML.
2. And to that, I'd neverworked with more than one CSS file but this also makes sense! Later this week I'll read over what you sent. Should I be good to, at this point, take what I put in the Table.css move the elements into the correct CSS files?
3. My current "class" project is building a 'library app' that has users input book info that I make into an object and put into an array and display on a page, which feels handy to me here.

**Comment by JarrettD5309** [comment]
Any class names that are specific to Table (such as tr, details-art, details-list, etc) should stay in the css file associated with the Table. Any styles that are meant to apply to the whole app or are specific to the App file (such as genre-button) should go in the css file associated with App.

**Comment by iloveMonday** [comment]
Alright, so the genre buttons are generated in App.tsx but I'm not sure which is the corresponding CSS.
I took a stab and put some universal css assignments into the stylesheet in the public folder. Is this correct? Or should they also go in the App.tsx stylesheet?

**Pull request merged**
